services:
  - type: web
    name: crypto-tracker-api
    runtime: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
    autoDeploy: true
